### ISSUE TITLE
Doesn't work in fastboot version 3.2.0-beta.2

### ISSUE THREAD

**Issue by erichonkanen** [mansona/ember-body-class#43]
In the latest version of [fastboot](https://github.com/ember-fastboot/ember-cli-fastboot/releases/tag/v3.2.0-beta.2) the body classes no longer render while in fastboot mode.

![image](https://user-images.githubusercontent.com/230757/130338317-01b596fe-617a-489e-b876-363ee6e4eb70.png)

Not exactly sure what's causing it or if it's something to change in this library or in fastboot but discovered it and thought I'd create this.

**Comment by mansona** [comment]
I've just fixed this! 🎉 

let me know if it works out for you

**Comment by erichonkanen** [comment]
@mansona sweet will try this out thanks!
