### ISSUE TITLE
Ability to toggle and bind classnames after the route is loaded?

### ISSUE THREAD

**Issue by milindalvares** [mansona/ember-body-class#5]

**Comment by chrissloey** [comment]
It's only on route [activate](http://emberjs.com/api/classes/Ember.Route.html#event_activate) right now. If you want to add it I'd be happy to accept a Pull Request. 👍

**Comment by bardzusny** [comment]
@chrissloey I just stumbled upon this very issue, and will be happy to address it in a PR - do you have any suggestions regarding potential implementation (ability to add/remove body classes after route init)?

My first thought is observer on route `classNames` property - can you see any other/better solution?

**Comment by mansona** [comment]
I'm pretty sure there is an observer in place now 🤔  but if this is something that people need do let me know and I'll re-open the issue 👍
